### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zalt00** [zalt00/Game2#7]
P0:
- [ ] faire le support de la base de donnée des collisions sur l'éditeur de niveau
- [ ] ajouter les slippery slopes aux resources

P1:
- [ ] ajout des structures dynamiques dans le monde + pins
- [ ] améliorer l'éditeur de structure au niveau de la création des pentes

P2:
- [ ] commande debug: capture d'écran
- [ ] commande debug: noclip
- [ ] blocs de rechargement de dash en l'air

P3:
- [ ] mode nuit quand on meurt
- [ ] ennemies
- [ ] musiques & effets sonores
- [ ] catapultes
- [ ] autres capacités

Terminées:
